GET http://localhost:9000
Authorization: Bearer 



###

POST http://localhost:9000/auth/register 

Content-Type: application/json

{
    "email" : "prasad@gmail.com",
    "password" : "1234"
}


###


###
POST http://localhost:9000/auth/login
Content-Type: application/json

{
    "email" : "kriss@gmail.com",
    "password" : "1213"
}




###

POST http://localhost:9000/auth/refresh-token 

Content-Type: application/json

    { 
      "refreshToken": 
      
      
      }
