GET http://localhost:9000
Authorization: Bearer 



###

POST http://localhost:9000/auth/register 

Content-Type: application/json

{
    "email" : "prasad@gmail.com",
    "password" : "1234"
}


###


###
POST http://localhost:9000/auth/login
Content-Type: application/json

{
    "email" : "kriss@gmail.com",
    "password" : "1213"
}




###

POST http://localhost:9000/auth/refresh-token 

Content-Type: application/json

    { 
      "refreshToken": 
      
      
      }

###

DELETE http://localhost:9000/auth/logout

Content-Type: application/json

   {
       "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTc1MDU5MzcsImV4cCI6MTY0OTA2MzUzNywiYXVkIjoiNjA2OGMyMGZmZDFhZWMwMzMzZjA1YTI1IiwiaXNzIjoiYmFuZGFyaS5jb20ifQ.67G6tGZvKCeaY3ji3o0czUi5zNxaC7PVEPTl8plK3gs"
    
    }